Document: bumblebee
Title: Debian bumblebee Manual
Author: <insert document author here>
Abstract: This manual describes what bumblebee is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/bumblebee/bumblebee.sgml.gz

Format: postscript
Files: /usr/share/doc/bumblebee/bumblebee.ps.gz

Format: text
Files: /usr/share/doc/bumblebee/bumblebee.text.gz

Format: HTML
Index: /usr/share/doc/bumblebee/html/index.html
Files: /usr/share/doc/bumblebee/html/*.html
