Document: virtualgl
Title: Debian virtualgl Manual
Author: <insert document author here>
Abstract: This manual describes what virtualgl is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/virtualgl/virtualgl.sgml.gz

Format: postscript
Files: /usr/share/doc/virtualgl/virtualgl.ps.gz

Format: text
Files: /usr/share/doc/virtualgl/virtualgl.text.gz

Format: HTML
Index: /usr/share/doc/virtualgl/html/index.html
Files: /usr/share/doc/virtualgl/html/*.html
